#!/bin/bash

if [[ $# == 0 ]]; then
    api-doc \
    -n sdaasd-asddasdas-asdasasd \
    -p "id|UUID|la de da" \
    -p "dasdas|UUID|la de da" \
    -r '200 - xxx|daasd asd asdasd asd |{"qw":12}' \
    -r '200 - xxx|daasd asd asdasd asd'
    exit
fi

# Initialize variables
params=()
request=""
responses=()
desc=""
name=""

# Parse remaining command-line arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        -d)
            shift
            if [[ $# -gt 0 ]]; then
                desc="$1"
                shift
            fi
            ;;
        -n)
            shift
            if [[ $# -gt 0 ]]; then
                name="$1"
                shift
            fi
            ;;
        -p)
            shift
            if [[ $# -gt 0 ]]; then
                params+=("$1")
                shift
            fi
            ;;
        -j)
            shift
            if [[ $# -gt 0 ]]; then
                request="$1"
                shift
            fi
            ;;
        -r)
            shift
            if [[ $# -gt 0 ]]; then
                responses+=("$1")
                shift
            fi
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Output parsed values
echo "Parameters: ${params[@]}"
echo "Request: $request"
echo "Response: $response"

echo
echo
echo "${name}" | sed "s/-/ /g; s/\b\(.\)/\U\1/g; s/^/## API: /; s/$/: \`${name}\`  →  \`JSON\`/"
echo
echo la la la la
echo
echo "### Request"
echo
if [[ "$params" != "" ]]; then
    for p in "${params[@]}"; do
        echo "$p" | sed "s/|/:/; s/|/\` - /; s/^/- \`/"
        echo
    done
fi
if [[ "$request" != "" ]]; then
    echo "\`\`\`json"
    echo "$request" | jq
    echo "\`\`\`"
fi
echo "### Response"
echo
if [[ "$responses" != "" ]]; then
    for r in "${responses[@]}"; do
        echo "$r" | sed "s/|/\` - /; s/^/- \`/; s/|.*//"
        json="$(echo $r | sed 's/.*|//')"
        if [[ "${json:0:1}" == "{" ]]; then
            echo "$json" | jq
        fi
        echo
    done
fi
echo "## Exceptions"
echo
if [[ "$params" != "" ]]; then
    for param in "${params[@]}"; do
        p="$(echo $param | sed 's/|.*//')"
        if [[ "$p" == "id" ]]; then
            echo "- If \`$p\` is passed and does not exist, return \`404 - Not Found\`: No record found for id: <id>."
            echo
        fi
        echo "- If $p is passed "
        echo
    done
fi
if [[ "$request" != "" ]]; then
    echo "- If the request contains a \`???\` which already exists for the specified ???, return: `409 - Conflict`: ????: <value> already exists."
fi