#!/bin/bash

help_text="
usage: <<FILENAME>> [options] <filename>
-h : This help text.
"

case $1 in
    -h|--help)
        echo "$help_text"
        exit
        ;;
esac

if [[ "$1" == "" ]]; then
  echo "$help_text"
fi