#!/bin/bash

help_text="
usage: gen_bash [options] <filename>
-h : This help text.
-b : Basic bash script only.
"

basic_yn=n
case $1 in
    -h|--help)
        echo "$help_text"
        exit
        ;;
    -b|--basic)
        basic_yn=y
        shift
        ;;
esac

new_file="$1"

if [[ -f "$new_file" ]]; then
    echo "Error: file: $1 already exists"
    exit 1
fi

if [[ $basic_yn == y ]]; then
    cat "$B/bash-basic-script-example" | sed "s/<<FILENAME>>/$1/" > "$new_file"
else
    cat "$B/bash-script-example" > "$new_file"
fi

read -p "Edit $1? c - code, g - gvim, n - No [cgN]: " cgn
cgn="${cgn^}"

if [[ $cgn == C ]]; then
    code "$new_file"
elif [[ $cgn == G ]]; then
    gvim "$new_file"
fi