#!/bin/bash
help_text="
NAME
  gen-bash-readme - Create a README.md for the bash scripts repo.

USAGE
  gen-bash-readme

DESCRIPTION
  Create a README.md for the bash scripts repo.

AUTHOR
  mjnurse.dev - 2020
"
help_line="Create a README.md for the bash scripts repo"

rme="$MJNWINROOT/MJN/github/bash/README.md"

echo "# Bash Scripts" > "$rme"
echo "" >> "$rme"

h -m >> "$rme"
