#!/bin/bash

if [[ "$1" == "" ]]; then
    file="/tmp/new-bash.tmp"
    tmp_file=Y
else
    tmp_file=N
    file="$1"
fi

if [[ -f $file ]]; then
  echo "$file - file already exists.  Terminating."
  exit
fi

read -p "Full or basic template? [fB]: " template_type

echo -e '#!/bin/bash' > $file
if [[ "$template_type^^" == "F" ]]; then
    echo 'help_text="
NAME
  '$1' - One line description.

USAGE
  '$1' [options] <parameters>

OPTIONS
  -x
    Description...

  -h|--help
    Show help text.

DESCRIPTION
  Description description description description.

AUTHOR
  Martin N 2025  
"
help_line="tbc"
web_desc_line="tbc"

try="Try ${0##*/} -h for more information"
tmp="${help_text##*USAGE}"
usage=$(echo "Usage: ${tmp%%OPTIONS*}" | tr -d "\n" | sed "s/  */ /g")' >> $file
else
    echo '
help_text=""
try="Try ${0##*/} -h for more information"
usage=""' >> $file
fi
echo '
if [[ "$1" == "" ]]; then
    echo "${usage}"
    echo "${try}"
    exit 1
fi

while [[ "$1" != "" ]]; do
    case $1 in
        -h|--help)
            echo "$help_text"
            exit
            ;;
        ?*)
            break
            ;;
    esac
    shift
done
' >> $file

chmod u+x $file

if [[ "$tmp_file" != "Y" ]]; then
    read -p "Edit file (MS Code/gVim): [cvN]? " cvn
    if [[ "${cvn^^}" == "C" ]]; then
        code $file
    elif [[ "${cvn^^}" == "V" ]]; then
        gvim $file
    else
        cat $file
    fi
else
    cat $file
    rm -f /tmp/new-bash.tmp
fi
