#!/usr/bin/env bash

# for f in c_*/*_notes.md; do awk -v dt="$(date -d '1 month ago' +%y-%m-%d)" 'NR==1 || ($1 ~ /[0-9]{2}-[0-9]{2}-[0-9]{2}/ && $1 > dt) {print FNR, $0 "\n"}' $f; done

help_line="Adds a note to a client's clientname_notes.md file"

# Terminal Colours
cdef="\x1b[39m" # default colour
cbla="\x1b[30m"; cgra="\x1b[90m"; clgra="\x1b[37m"; cwhi="\x1b[97m"
cred="\x1b[31m"; cgre="\x1b[32m"; cyel="\x1b[33m"; cblu="\x1b[34m"; cmag="\x1b[35m"; ccya="\x1b[36m";
clred="\x1b[91m"; clgre="\x1b[92m"; clyel="\x1b[93m"; clblu="\x1b[94m"; clmag="\x1b[95m"; clcya="\x1b[96m"

cd "$DOCS"

mode=add
while [[ $# -gt 0 ]]; do
    case "$1" in
        -e|--edit)
            mode=edit
            ;;
        -h|--help)
            echo "Usage:   pn [options] [<client> [<note>]]"
            echo "Options:"
            echo "  -e, --edit    Edit the client's notes file"
            echo "  -l, --list    List the first 30 lines of the client's notes file"
            echo "  -h, --help    Show this help message"
            echo "Example: pn client_name 'This is a note.'"
            exit
            ;;
        -l|--list)
            mode=list
            ;;
        -r|--recent)
            if [[ "$2" != "" ]]; then
                filter="*$2*"
            fi
            for c in c_*$filter; do
                if [[ "$c" == "c_archive"* ]]; then
                    continue
                fi
                f="$c/${c#c_}_notes.md"
                if [[ -f "$f" ]]; then
                    awk -v dt="$(date -d '1 month ago' +%y-%m-%d)" \
                        'NR==1 {print "\n--------------------------------------------------\n" $0, "('$c')"} 
                        ($1 ~ /[0-9]{2}-[0-9]{2}-[0-9]{2}/ && $1 > dt) {print "\n" $0}' $f | mdc
                fi
            done
            exit
            ;;
        *)
            break
            ;;
    esac
    shift
done


if [[ $# -gt 0 ]]; then
    client="${1,,}"
    if [[ ! -d "c_${client}" ]]; then
        echo "Client directory c_${client} does not exist."
        exit
    fi
    shift
else
    COLUMNS=1
    PS3="Choose client: "
    select client in $(ls -d c_*/ | sed 's/c_//; s/\/$//'); do
        [ -n "$client" ] && break
    done
fi

if [[ ! -f  "c_${client}/${client}_notes.md" ]]; then
    echo -e "# ${client^^}\n\n" > "c_${client}/${client}_notes.md"
fi

if [[ "$mode" == "list" ]]; then
    head -n 30 "c_${client}/${client}_notes.md" | mdc
    exit
fi

if [[ "$mode" == "edit" ]]; then
    code "c_${client}/${client}_notes.md"
    exit
fi

if [[ $# -lt 1 ]]; then
    read -p "Notes: " note
    if [[ -z "$note" ]]; then
        exit
    fi
else
    note="$*"
fi

note="$(date +%y-%m-%d): $note"
echo
echo "Add: $note"
read -p "To:  c_${client}/${client}_notes.md? (yN) " confirm
if [[ "${confirm^^}" == "Y" ]]; then
    sed -i "2a${note}\n" "c_${client}/${client}_notes.md"
fi
